---
- name: Copy systemd template
  template:
    src: "templates/kibana.service.j2"
    dest: "/etc/systemd/system/kibana.service"

- name: Re/Start Kibana
  service:
    name: "kibana.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
